### ISSUE TITLE
Running examples fails

### ISSUE THREAD

**Issue by mkondel** [coldiary/react-image-mapper#12]
Here is the log from my command line:

```bash
$ yarn && yarn examples
yarn install v1.10.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.61s.
yarn run v1.10.1
$ gulp dev:server
/home/max/Documents/react-image-mapper/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/home/max/Documents/react-image-mapper/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/home/max/Documents/react-image-mapper/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/max/Documents/react-image-mapper/node_modules/react-component-gulp-tasks/tasks/release.js:1:73)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by coldiary** [comment]
This looks like a bug from require-dir package.
It has been resolved in 0.3.2. I'll upgrade the dependency.

**Comment by mkondel** [comment]
I am on v8.12.0

**Comment by CharanRoot** [comment]
@coldiary 
I am facing the same issue with Node v8.9.4. the main issue was Node 8  `require.extensions ` initilized changed due to securty reasons. so you can rebuild your code with latest Node

In Node 6 require.extensions was initialized with {}. In Node 8, it is initialized with Object.create(null).

A test like

if (require.extensions.hasOwnProperty(ext) {
cannot work in Node 8 and higher due to the way require.extensions is initialized with Object.create(null). (Details below.)

The code above has to become:

if (Object.prototype.hasOwnProperty.call(require.extensions, ext)) {
You still have to use hasOwnProperty for compatibility with Node 6. Once compatibility with 6 is dropped, it could be reduced to if (ext in require.extensions) { because the distinction between own and inherited properties is meaningless for objects created by Object.create(null).

more info [Link]( https://stackoverflow.com/a/45545503 )

**Comment by coldiary** [comment]
I plan to rewrite this package entirely to a more recent version of node, maybe in Typescript, whenever I'll have time to do it.
In the mean time, if you want it to update sooner, I'll give a look to any PR posted.

**Comment by MichaelLiss** [comment]
I am using "node": "8.11.4" with no issues.

**Comment by Mvbraathen** [comment]
Did not work with node version "8.11.4" for me, but works with version 6.
